In [23]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score, classification_report

In [24]:
apple = pd.read_csv('../Yahoo_Finance/Apple/AAPL_historical_stock.csv')
apple

,Date,Open,High,Low,Close,Adj Close,Volume
0,1980-12-12,0.128348,0.128906,0.128348,0.128348,0.098207,469033600
1,1980-12-15,0.122210,0.122210,0.121652,0.121652,0.093083,175884800
2,1980-12-16,0.113281,0.113281,0.112723,0.112723,0.086251,105728000
3,1980-12-17,0.115513,0.116071,0.115513,0.115513,0.088386,86441600
4,1980-12-18,0.118862,0.119420,0.118862,0.118862,0.090949,73449600
...,...,...,...,...,...,...,...
11497,2026-07-29,339.730011,344.570007,337.350006,338.190002,338.190002,56090800
11498,2026-07-30,333.100006,334.750000,329.589996,333.429993,333.429993,74817800
11499,2026-07-31,304.809998,310.690002,300.000000,308.910004,308.910004,132489100
11500,2026-08-03,309.579987,311.799988,302.559998,303.420013,303.420013,74824300
11501,2026-08-04,302.725006,304.679993,301.320007,304.614990,304.614990,9366275

In [30]:
apple['Date'] = apple['Date'].str.extract(r'(\d{4}-\d{1,2})')
apple

,Date,Open,High,Low,Close,Adj Close,Volume
0,1980-12,0.128348,0.128906,0.128348,0.128348,0.098207,469033600
1,1980-12,0.122210,0.122210,0.121652,0.121652,0.093083,175884800
2,1980-12,0.113281,0.113281,0.112723,0.112723,0.086251,105728000
3,1980-12,0.115513,0.116071,0.115513,0.115513,0.088386,86441600
4,1980-12,0.118862,0.119420,0.118862,0.118862,0.090949,73449600
...,...,...,...,...,...,...,...
11497,2026-07,339.730011,344.570007,337.350006,338.190002,338.190002,56090800
11498,2026-07,333.100006,334.750000,329.589996,333.429993,333.429993,74817800
11499,2026-07,304.809998,310.690002,300.000000,308.910004,308.910004,132489100
11500,2026-08,309.579987,311.799988,302.559998,303.420013,303.420013,74824300
11501,2026-08,302.725006,304.679993,301.320007,304.614990,304.614990,9366275

In [26]:
apple.dtypes

Date             str
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object

In [27]:
inflation = pd.read_csv('../FRED/inflation.csv')
inflation

    observation_date  CPIAUCSL
0         1947-01-01    21.480
1         1947-02-01    21.620
2         1947-03-01    22.000
3         1947-04-01    22.000
4         1947-05-01    21.950
..               ...       ...
949       2026-02-01   327.460
950       2026-03-01   330.293
951       2026-04-01   332.407
952       2026-05-01   333.979
953       2026-06-01   332.568

[954 rows x 2 columns]

In [28]:
inflation['observation_date'] = inflation['observation_date'].str[:-3]
inflation

    observation_date  CPIAUCSL
0            1947-01    21.480
1            1947-02    21.620
2            1947-03    22.000
3            1947-04    22.000
4            1947-05    21.950
..               ...       ...
949          2026-02   327.460
950          2026-03   330.293
951          2026-04   332.407
952          2026-05   333.979
953          2026-06   332.568

[954 rows x 2 columns]

In [29]:
inflation.dtypes

observation_date        str
CPIAUCSL            float64
dtype: object

In [ ]:
# apple['Date'] = pd.to_datetime(apple['Date']).dt.strftime('%Y-%m')
# inflation['Date'] = pd.to_datetime(inflation['Date']).dt.strftime('%Y-%m')
# inflation
# apple

In [ ]:
# inflation = inflation.rename(columns={'observation_date': 'Date'})
# merged = pd.merge(apple, inflation, on='Date', how='inner')